### ISSUE TITLE
[BUG] - [PF2e]: Split currency is not working

### ISSUE THREAD

**Issue by xavien12** [fantasycalendar/FoundryVTT-ItemPiles#184]
**Describe the bug**
Split currency is not working. 

**To Reproduce**
1. Create a loot actor and make it an item pile
2. Put currency (gold, silver, cp) in it (any amount that is larger than the size of the party)  
3. Click on split currency
4. Nothing happens

**Expected behavior**
Currency should be split among the party, with the rest which cannot be split be left in the item pile

**Setup:**
 - Foundry Version: 10.228
 - System Version: 4.3.4
 - Item Piles Version: 2.2.10
 - Browser & version: Firefox 107.0b9 (64-bit)

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Additional context**
I disabled all other modules, than the ones required with "find the culprit" and the issue still persist

**Comment by xavien12** [comment]
Pf2e

**Comment by A1exanderWebb** [comment]
I have the same issue. (Foundry v10.290, DND5e v2.0.3, Item Piles v2.2.12, no other modules (except for dependencies as above))

The error has persisted since installing the module several updates ago, installing and reinstalling have not fixed it. I get the same error regardless of the number of players the currency is being split between, and regardless of the quantities and types of currencies being split. I have pasted a copy of the error below:

Uncaught (in promise) TypeError: uuid.startsWith is not a function
[Detected 1 package: item-piles]
    at _parseUuid (foundry.js:4135)
    at fromUuidSync (foundry.js:4099)
    at Function._executeItemPileMacro (private-api.js:1042)
    at Function._splitItemPileContents (private-api.js:1495)

**Comment by xavien12** [comment]
For me when i check the log the error is 
Uncaught (in promise) TypeError: item.toObject is not a function
[Detected 2 packages: item-piles, socketlib]

**Comment by Avitale34** [comment]
I am on dnd 5e and also can not split currency. Getting this error.

foundry.js:4135 Uncaught (in promise) TypeError: uuid.startsWith is not a function
[Detected 1 package: item-piles]
    at _parseUuid (foundry.js:4135:13)
    at fromUuidSync (foundry.js:4099:49)
    at PrivateAPI._executeItemPileMacro (private-api.js:1042:26)
    at PrivateAPI._splitItemPileContents (private-api.js:1495:16)

**Comment by Haxxer** [comment]
Fixed in 2.2.13

**Comment by xavien12** [comment]
I just want to say it still does not work with pf2e. I still get the same error. Current version of foundry, pf2e and itempile.

**Comment by Haxxer** [comment]
Fixed again in 2.3.0
