### ISSUE TITLE
[BUG] - Item Piles are not working for me in Fallout 2d20

### ISSUE THREAD

**Issue by BlueShizuka** [fantasycalendar/FoundryVTT-ItemPiles#192]
**Describe the bug**
When dragging an item onto the map and then opening the item pile the only thing displayed is currency (caps). Dragging another item onto the pile also does not add that item to the pile. There is also no pop-up window asking if I'd like to add this item to the loot pile. In short, it's impossible for me to add items to item piles besides currency.

**To Reproduce**
1. Use Fallout 2d20 System
2. Update everything to latest version (I've also tried version 9 of Foundry with previous version of Item Piles which did not work)
3. Attempt to create an item pile by dragging and dropping 

**Expected behavior**
If it's not just a "me problem" then what should happen is there will be no pop up window asking you to confirm anything. You should also see no items in the item pile, only currency.

**Setup:**
 - Foundry Version: 10
 - System Version: 10
 - Item Piles Version: 2.2.13
 - Browser & version Google Chrome 107.0.5304.107

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib
 - Too many to list but I've tried deactivating everything except for the above 3 and had the same result

**Additional context**
I've looked at Youtube videos of how it should work and I can see it doesn't work as it should so I don't believe it's user error. I've also been in a Fallout 2d20 game that used this module and it seemed to work fine then too but I'm unsure of what versions the GM used. 

Screen recording of problem:
https://user-images.githubusercontent.com/118239873/201824573-77e5108f-c341-4357-b87f-1bd78c71ee77.mp4

**Comment by Haxxer** [comment]
This was fixed, delete your default item pile to let the module recreate it and it is fixed in the latest version

**Comment by BlueShizuka** [comment]
I’ve done as you asked and it’s still not working. Deleting it has done nothing as well as uninstalling and reinstalling.

**Comment by BlueShizuka** [comment]
I can confirm it now works on my end. Thank you so much for the good work and speedy responses. You’re a legend!
