### ISSUE TITLE
addItems function has several errors, and API description of turnTokensIntoItemPiles not clear.

### ISSUE THREAD

**Issue by Freeze021** [fantasycalendar/FoundryVTT-ItemPiles#38]
Instead of bothering you on Discord, posting my findings here in the correct channel/workflow ;)

1) I think some search & replace has gone awry in the `addItems` function:

```
static async addItems(target, items, { interactionId = false } = {}) {

        const hookResult = Hooks.call(HOOKS.ITEM.PRE_ADD, target, items, interactionId);
        if (hookResult === false) return;

        const targetUuid = lib.is_UUID(target) ? target : lib.getUuid(target);
        if (!targetUuid) throw lib.custom_error(`AddItems | Could not determine the UUID, please provide a valid target`, true)

        items = items.map(itemData => {
            let item;
            if(itemData.item instanceof Item){  //should be: itemData instanceof Item
                item = itemData.item.toObject(); // should be: itemData.toObject();
            }else{
                item = itemData.item;  //should be: itemData;
            }
            return {
                item: item,
                quantity: itemData?.quantity ?? getProperty(foundActorItem.data, API.ITEM_QUANTITY_ATTRIBUTE) //should be item.data
            }
        });

        if (interactionId && typeof interactionId !== "string") {
            throw lib.custom_error(`AddItems | interactionId must be of type string or false`);
        }

        return itemPileSocket.executeAsGM(SOCKET_HANDLERS.ADD_ITEMS, targetUuid, items, game.user.id, { interactionId });
    }
```
2) maybe it is me being stupid, but:
the API says `turnTokensIntoItemPiles(tokenDocument, pileSettings, tokenSettings)` where pileSettings and tokenSettings are objects. However the function is: `static async turnTokensIntoItemPiles(targets, { pileSettings = {}, tokenSettings = {} } = {})` which means that you have two params, not three, of which the second param is an object made of two objects, ie, pileSettings and tokenSettings. Does that make sense why it is confusing in the documentation?

**Comment by Haxxer** [comment]
Good catch, I will update the API

**Comment by Haxxer** [comment]
Fixed in 1.2.4 hotfix

**Comment by Freeze021** [comment]
You did miss the most of the comments in the addItem function, meaning it is still broken in 1.2.5

**Comment by Haxxer** [comment]
I've got 1.3.0 in the pipe which addresses this

**Comment by Freeze021** [comment]
wow quick! Ok great :)

**Comment by Haxxer** [comment]
I believe this has been resolved in 1.2.7
