### ISSUE TITLE
[Better roll tables quantity] - [pf1e] - Quantity always one item.

### ISSUE THREAD

**Issue by dxwarlock** [fantasycalendar/FoundryVTT-ItemPiles#447]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
With 2.7.11 and the better roll tables addition, it does not seem to obey/use the total count. I made the table with 1 entry with 2d4 results. No matter how many times I 'Roll all tables" I get one result: 

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/ecc24737-cf40-40c2-bf44-c51e498f174f)

**To Reproduce**
Set a table to a better roll table, set quantity of rolls for that table item to anything but one. 

**Expected behavior**
To populate with number of items off that table, in accordance with the value set.
Above example would roll 1 time on that table (in item pile settings), and return 2d4 items (table setting).

**Comment by Haxxer** [comment]
Aaaactually fixed in 2.7.12 lol

**Comment by dxwarlock** [comment]
Thanks, sorry for all the hassle :)

**Comment by dxwarlock** [comment]
I still get the same results on 2.7.12
is there some implementation I need to do for itempiles?

**Comment by Haxxer** [comment]
It should work? What type of rolltable is it in the rolltable configuration? Better rolltable?

**Comment by dxwarlock** [comment]
Yes. This is my test table setup:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/1b25dd59-b492-47db-8826-cc42f6f633b6)

If I roll on the table directly I get this in chat:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/c51ae2d6-8c53-4f3c-b7fb-beb36e0bd9e8)

This is the merchant setup with me hitting "roll all tables"
It should have at least 2 items as table is 2d2:
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/520536/31815b3e-934a-4e2f-9f97-1fe941bae08e)

**Comment by Haxxer** [comment]
Seems like better rolltables are not patching the `drawMany` function, which ignores the better rolltables formulas. I will look into this later.

**Comment by dxwarlock** [comment]
Not a problem, take your time more a QoL feature.
As all my tables I used was better tables for loot/chests in v9, but the lootNPC sheet is no more in v11. So came to item piles (it's WAY better anyway 🥇) And would take 3x the tables, and redoing them all, without better tables to make them work the same way.

**Comment by Haxxer** [comment]
Fixed in 2.7.13
