### ISSUE TITLE
[BUG] - Can't add currency as GM

### ISSUE THREAD

**Issue by Ikabodo** [fantasycalendar/FoundryVTT-ItemPiles#60]
**Describe the bug**
You can't add currency from the GM-window when trading with a player.

```js
foundry.js:316 TypeError: currencies.filter is not a function
[Detected 1 package: item-piles]
    at Module.getActorCurrencies (modules/item-piles/scripts/lib/lib.js:377:10)
    at DropCurrencyDialog.getData (modules/item-piles/scripts/formapplications/drop-currency-dialog.js:64:31)
    at DropCurrencyDialog._render (foundry.js:3062:29)
    at DropCurrencyDialog._render (foundry.js:3764:17)
    at DropCurrencyDialog.render (foundry.js:3021:10)
    at modules/item-piles/scripts/formapplications/drop-currency-dialog.js:48:57
    at new Promise (<anonymous>)
    at Function.query (modules/item-piles/scripts/formapplications/drop-currency-dialog.js:47:16)
    at TradingApp.addCurrency (modules/item-piles/scripts/formapplications/trading-app.js:181:56)
    at HTMLAnchorElement.<anonymous> (modules/item-piles/scripts/formapplications/trading-app.js:363:18)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at HTMLAnchorElement.v.handle (jquery.min.js:2:41048)
```

I am not sure if this is intended or not. But it is throwing an error so I assume it's not intended. :)

**To Reproduce**
1. As a GM, open trade with player, with a token as actor
2. Let player accept
3. Click "+Add Currency (GM Mode)"

**Expected behavior**
You should be able to add currency in the trade.

**Setup:**
 - Foundry Version: 9.249
 - Item Piles Version: 1.4.0
 - OS: Windows 10
 - Browser: Chrome

**Active modules:**
 - Item Piles
 - libwrapper
 - socketlib

**Comment by Ikabodo** [comment]
> Which system is this with?

5e, default currency settings.

**Comment by Shuggaloaf** [comment]
Also getting this.

 @Ikabodo If you didn't already find this, a workaround is to open the actor sheet and add the currency there.

**Comment by Haxxer** [comment]
Fixed in 1.4.1

**Comment by Shuggaloaf** [comment]
I'm on 1.4.1 and noticed the behavior. 

There definitely still seems to be an issue with Platinum. Adding coins sometimes adds PP but not total amount you try to add. Sometimes it adds nothing at all. 

**Info** 
-     Foundry Version: 0.8.9
-     System: Dnd5e 1.5.6
-     Item Piles Version: 1.4.1
-     OS: Windows 10
-     Browser: Chrome/Electron

**Comment by Shuggaloaf** [comment]
I'm not seeing different modes for add currency. I am doing this as the GM if that is what you mean?

This gif may help. It's a little too zoomed in but still shows all the relevant info ...
<img src="https://user-images.githubusercontent.com/79543184/153632471-26c2d946-bacd-44db-8d86-afd31db1d861.gif" width="50%">

**Comment by Haxxer** [comment]
Ah, I thought you were talking about the Trade Interface, that is the item piles themselves. I'll investigate.

**Comment by Shuggaloaf** [comment]
I see now this post mentioned trading. Sorry I missed that. Would you like me to open a new issue?

Also, I see I was not crazy when I said I thought other currency was having an issue. Now it's happening with PP and GP. Yesterday I'm pretty sure it was not adding to _any_ currency type.

https://user-images.githubusercontent.com/79543184/153634080-5d257972-7959-4320-bc7b-c08e9704f191.mp4

**Comment by Haxxer** [comment]
Yes please.
