### ISSUE TITLE
[BUG] - [Item Piles] - MIssing Localizations

### ISSUE THREAD

**Issue by Kharmans** [fantasycalendar/FoundryVTT-ItemPiles#629]
Some localizations are not present on en.json.

![image](https://github.com/user-attachments/assets/5309ca97-cb40-40d0-99b4-4f8b0b79e59e)
![image](https://github.com/user-attachments/assets/fb993bf6-455e-4abd-9da9-0093f451677f)
![image](https://github.com/user-attachments/assets/b95d183d-7f86-442e-89a2-e02e803fc096)
![image](https://github.com/user-attachments/assets/aacfed57-cc49-4207-ac05-7830f33e4d58)

**Comment by Haxxer** [comment]
Fixed in 3.0.10

**Comment by Kharmans** [comment]
> Fixed in 3.0.10

Thanks! But the first one was the only that still doesn't have a localization. The **Trade** button.

**Comment by Haxxer** [comment]
It does have a localization. You have another module that changes it, namely Rest Recovery.
