### ISSUE TITLE
[BUG] - GENERAL? - Purchase Options (and Selling Options) no longer work properly as of 3.1.1. 

### ISSUE THREAD

**Issue by Karuna053** [fantasycalendar/FoundryVTT-ItemPiles#647]
**Are you on the latest version of Item Piles?**
Yes

**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Purchase Options no longer work properly as of 3.1.1 (and by extension also Selling Options). Cannot buy items with Purchase Options anymore.

**To Reproduce**

1. Enable **Disable Normal Cost** and **Purchase Option as Selling Option**
2. Add **Purchase Options** and **Selling Options**
3. Select "Update Item".
4. NPC vendor does not allow you to buy with Purchase Options at all

**Expected behavior**
NPC vendor should allow you to buy things in the Purchase Options, right now, you cannot do that.
NPC vendor should also respect the option to "Disable Normal Cost", right now, it does not respect the option.

**Screenshots**
![image](https://github.com/user-attachments/assets/3c9643a0-3027-44c4-b30f-8d7f1376eea6)

**Setup:**

- Foundry Version: [e.g. 11.315]
- System Version: [e.g. Custom System Builder 3.2.5]
- Item Piles Version: [e.g. 3.1.1]
- Browser & version [e.g. Electron App]

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Comment by Haxxer** [comment]
Do you have this enabled? If so, disable it.

![image](https://github.com/user-attachments/assets/8dc28072-7142-41ba-a1e9-1fc2fc669214)

**Comment by Haxxer** [comment]
I now realize that is counterintuitive, and will fix

**Comment by Karuna053** [comment]
![image](https://github.com/user-attachments/assets/6aa4da6f-6cef-4d39-a3ac-221b3fef8cda)

I tried disabling the option you mentioned, but the items that require secondary currency to purchase in Purchase Options and Selling Options still bugs out (Reflex and Tremor above).

**Comment by Haxxer** [comment]
Fixed in 3.1.2

**Comment by Karuna053** [comment]
As of 3.1.2, secondary currencies still cannot be used in both Purchase Options and Selling Options, the option to select the choice is there, but it does not show up.

![image](https://github.com/user-attachments/assets/e48534e6-4a94-4411-8bca-781c9511ae2a)

Same case if the primary currency is combined with secondary currency. 

![image](https://github.com/user-attachments/assets/661249f5-01d8-46bb-ab47-b89048dee8b6)

 

![image](https://github.com/user-attachments/assets/780d7521-2d2b-40a8-b370-a84fc8367fbd)

**Comment by Haxxer** [comment]
Any errors in your console?

**Comment by Haxxer** [comment]
Could you please get in touch through Discord? I am not able to reproduce your issues, and would like to test on your server.

My discord handle is wasp

**Comment by Karuna053** [comment]
Sure! I've pinged you in the discord server.

**Comment by Haxxer** [comment]
Fixed in 3.1.3
